### ISSUE TITLE
Failed to synchronize

### ISSUE THREAD

**Issue by forchain** [Qitmeer/qitmeer#200] opened 2019-11-29 12:15 UTC
Can reproduce with this block data on v0.8.2

https://drive.google.com/file/d/10o8u2PXGxdbLt_IBClqsrWqs8IMdBxVd/view?usp=sharing

**Comment by yatingzhou** [comment] 2019-11-29 16:03
$ ./cli-local.sh peerinfo|jq '"\(.[].graphstate.mainorder),\(.[].graphstate.mainheight)"'
"881,451"
"1188,451"
"573,451"
"1725,451"
"1753,451"
"1483,451"
"881,735"
"1188,735"
"573,735"
"1725,735"
"1753,735"
"1483,735"
"881,186"
"1188,186"
"573,186"
"1725,186"
"1753,186"
"1483,186"
"881,1207"
"1188,1207"
"573,1207"
"1725,1207"
"1753,1207"
"1483,1207"
"881,1232"
"1188,1232"
"573,1232"
"1725,1232"
"1753,1232"
"1483,1232"
"881,990"
"1188,990"
"573,990"
"1725,990"
"1753,990"
"1483,990"

这是我们抓取的节点同步情况。

**Comment by lochjin** [comment] 2019-12-02 00:59
> Can reproduce with this block data on v0.8.2
> 
> https://drive.google.com/file/d/10o8u2PXGxdbLt_IBClqsrWqs8IMdBxVd/view?usp=sharing

https://github.com/Qitmeer/qitmeer/pull/202

**Comment by forchain** [comment] 2019-12-02 05:44
#202 has fixed this one, but there are new problem

**Comment by forchain** [comment] 2019-12-02 08:59
https://drive.google.com/file/d/1fzMFjb0jrOowGo7NXCD-JKiKlW0SHGwl/view?usp=sharing

**Comment by Noctis0227** [comment] 2019-12-02 09:06
[47.74.248.20.tar.gz](https://github.com/Qitmeer/qitmeer/files/3910322/47.74.248.20.tar.gz)
[119.27.165.37.tar.gz](https://github.com/Qitmeer/qitmeer/files/3910323/119.27.165.37.tar.gz)

**Comment by lochjin** [comment] 2019-12-05 02:45
> #202 has fixed this one, but the initial downloading cannot be finished

https://github.com/Qitmeer/qitmeer/commit/c61d00852d730547c5ae6687dcbf1c961e4fde14

**Comment by forchain** [comment] 2019-12-08 20:28
Synchronization stuck and cannot exit by ctrl+C, so I had to kill it by force. It recovered rapidly after reboot.

2019-12-09|00:42:45.455 [INFO ] Processed 3 blocks in the last 39.61s (3 transactions, order 3632, 2019-12-09 00:42:07 +0800 CST) module=blkmanager
2019-12-09|00:42:45.456 [INFO ] Your synchronization has been completed.  module=blkmanager
。。。。
2019-12-09|00:44:35.395 [WARN ] No sync peer candidates available   module=blkmanager
2019-12-09|00:44:37.278 [INFO ] Peer 207.148.95.219:28130 (outbound) appears to be stalled or misbehaving, block timeout -- disconnecting
2019-12-09|00:44:37.278 [INFO ] Lost peer                           module=blkmanager peer="207.148.95.219:28130 (outbound)"
2019-12-09|00:44:38.395 [WARN ] No sync peer candidates available   module=blkmanager
。。。。
2019-12-09|00:45:26.395 [WARN ] No sync peer candidates available   module=blkmanager
2019-12-09|00:45:26.573 [INFO ] New valid peer: 207.148.95.219:28130 (outbound),user-agent:qitmeer:0.8.4 module=blkmanager
2019-12-09|00:45:26.573 [INFO ] Syncing to state (3640,2773,2775,3648,1) from peer 207.148.95.219:28130 cur graph state:(3632,2766,2768,3640,1) module=blkmanager
2019-12-09|00:45:33.652 [INFO ] Processed 1 block in the last 2m48.19s (1 transaction, order 3633, 2019-12-09 00:42:27 +0800 CST) module=blkmanager



^C2019-12-09|03:46:46.545 [INFO ] Shutting down...                    Received signal=interrupt
2019-12-09|03:46:46.576 [INFO ] Gracefully shutting down the server...
2019-12-09|03:46:46.576 [INFO ] Stopping Server                     module=node
2019-12-09|03:46:46.585 [WARN ] Stopping P2P Server
2019-12-09|03:46:46.585 [WARN ] wait for P2P stop ...
2019-12-09|03:46:46.591 [INFO ] Connection manager stopped
2019-12-09|03:46:46.592 [INFO ] Address manager shutting down
2019-12-09|03:46:46.593 [WARN ] P2P Server stopped
2019-12-09|03:46:46.593 [INFO ] try stop bm                         module=node
2019-12-09|03:46:46.595 [INFO ] Block manager shutting down         module=blkmanager
2019-12-09|03:46:46.595 [INFO ] Wait For Block manager stop ...     module=blkmanager
^[[A


^C2019-12-09|03:55:10.667 [INFO ] Already shutting down...            Received signal=interrupt
。。。。
^C2019-12-09|03:58:30.086 [INFO ] Already shutting down...            Received signal=interrupt
[1]    27035 killed     ./build/bin/qitmeer -A ~/.qitmeerd-v0.8.4

ubuntu@Chengdu ~/github.com/lochjin/qitmeer (master) $ ./build/bin/qitmeer -A ~/.qitmeerd-v0.8.4
2019-12-09|04:03:03.911 [INFO ] System info                         Qitmeer Version=0.8.4+dev-d994212 Go version=go1.13
2019-12-09|04:03:03.913 [INFO ] System info                         UUID=49539022-63aa-48d3-8fed-3d6d084ad214
2019-12-09|04:03:03.914 [INFO ] System info                         Home dir=/home/ubuntu/.qitmeerd-v0.8.4
2019-12-09|04:03:03.916 [INFO ] Loading block database              dbPath=/home/ubuntu/.qitmeerd-v0.8.4/data/testnet/blocks_ffldb
2019-12-09|04:03:03.952 [INFO ] Detected unclean shutdown - Repairing... module=database
2019-12-09|04:03:03.960 [INFO ] Database sync complete              module=database
2019-12-09|04:03:03.963 [INFO ] Block database loaded
2019-12-09|04:03:03.967 [INFO ] Starting Server                     module=node
2019-12-09|04:03:03.968 [INFO ] Transaction index is enabled        module=node
2019-12-09|04:03:03.969 [INFO ] anticone size:6                     module=blockdag
2019-12-09|04:03:03.984 [INFO ] Loading dag ...                     module=blockchain
2019-12-09|04:03:04.133 [INFO ] Dag loaded:loadTime=148.344667ms    module=blockchain
2019-12-09|04:03:04.458 [INFO ] DAG Type:phantom                    module=blockchain
2019-12-09|04:03:04.460 [INFO ] Blockchain database version         module=blockchain chain=1 compression=1 index=1
2019-12-09|04:03:04.462 [INFO ] Chain state:totaltx=3637 tipsNum=3 mainOrder=3628 total=3636 module=blockchain
2019-12-09|04:03:04.463 [INFO ] hash=1484f814cdc341a0a9a812c6e3eb92fa066ae8bd1ef9e2bfc970eb3cad4256d1,order=3628,work=846644845316567083723374 module=blockchain
2019-12-09|04:03:04.463 [INFO ] hash=2203d6f2171e0a25e08db3c25a6100f1530d21a825eda5127d7f289ff9af8ad9,order=uncertainty,work=369834160247818732715688 module=blockchain
2019-12-09|04:03:04.463 [INFO ] hash=2840459a7d509847d9b8d72e99ca4ca9e5bcbbf353b00d7826ceaad174fcabe6,order=uncertainty,work=618443425890461093447982 module=blockchain
2019-12-09|04:03:04.463 [INFO ] Starting tx manager                 module=txmanager
2019-12-09|04:03:04.464 [INFO ] RPC server listening on             addr=0.0.0.0:28131
2019-12-09|04:03:04.468 [INFO ] Loaded 2 addresses from file '/home/ubuntu/.qitmeerd-v0.8.4/data/testnet/peers.json'
2019-12-09|04:03:04.469 [INFO ] Connection manager started
2019-12-09|04:03:04.471 [INFO ] P2P Server listening on             addr=0.0.0.0:28130
2019-12-09|04:03:04.471 [INFO ] P2P Server listening on             addr=[::]:28130
2019-12-09|04:03:04.551 [INFO ] New valid peer: 47.103.194.115:28130 (outbound),user-agent:qitmeer:0.8.4 module=blkmanager
2019-12-09|04:03:04.554 [INFO ] Syncing to state (4326,3361,3363,4336,3) from peer 47.103.194.115:28130 cur graph state:(3628,2762,2764,3636,1) module=blkmanager
2019-12-09|04:03:04.694 [INFO ] New valid peer: 207.148.95.219:47030 (inbound),user-agent:qitmeer:0.8.4 module=blkmanager
2019-12-09|04:03:05.619 [INFO ] tried to overwrite transaction e4bd31f42607c66609df4e3551288a9ae69f02f7b2a704993a98c955594fc22c at block 425b8965810ded0fe2b481e76079c39f6baf9fab71b2d0e8f073b74e8a881398 that is not fully spent module=blockchain
2019-12-09|04:03:10.464 [INFO ] Syncing to state (4329,3362,3364,4337,1) from peer 207.148.95.219:47030 cur graph state:(4128,3183,3185,4136,1) module=blkmanager
2019-12-09|04:03:24.228 [INFO ] 1 addresses found from DNS seed seed.dag.team
2019-12-09|04:03:32.528 [INFO ] Processed 501 blocks in the last 28.55s (1501 transactions, order 4129, 2019-12-09 03:00:00 +0800 CST) module=blkmanager
2019-12-09|04:03:33.131 [INFO ] Your synchronization has been completed.  module=blkmanager

**Comment by dindinw** [comment] 2019-12-19 01:19
@forchain The synchronization issue has been fixed by the latest version `0.8.4`, the issue is closed

**Closed by dindinw** 2019-12-19 01:19 UTC
