### ISSUE TITLE
How can i get CB1 - CB4

### ISSUE THREAD

**Issue by peterpan0708** [Qitmeer/qitmeer#402] opened 2020-11-28 05:44 UTC
I'm building a qitmeer mining pool, but now I have trouble getting the CB1 - CB4.
I 'm using the qit-cli rpc tool , and from "getBlockTemplate coinbaseTxn" method, I got the following reply
![image](https://user-images.githubusercontent.com/36805830/100494759-c1fb1f80-317f-11eb-9952-8a1f6e58ebfa.png)

Maybe i can do something with the coinbaseTxn data to get CB1 - CB4 ? or Is there a simple way to get CB1 - CB4

**Comment by 5dao** [comment] 2020-11-30 02:14
Duplicate of #https://github.com/Qitmeer/qitmeer/issues/228

**Closed by 5dao** 2020-11-30 02:14 UTC
